service: realworld-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  
  signIn:
    handler: src/users.signIn
    events:
      - httpApi:
          path: /signIn
          method: post
  signUp:
    handler: src/users.signUp
    events:
      - httpApi:
          path: /api/users
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
