name: Run test on open pull request
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  deploy:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: Run testing
      run: yarn test